// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Reductive = require("reductive/lib/js/src/reductive.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Extension$ReductiveDevTools = require("./extension.bs.js");
var Utilities$ReductiveDevTools = require("./utilities.bs.js");

var evalMethod = ( 
    function evalMethod(action, obj) {
      if (typeof action === 'string') {
        return new Function('return ' + action).call(obj);
      }

      let interpretArg = (arg) => {
        return new Function('return ' + arg)();
      };

      let evalArgs = (inArgs, restArgs) => {
        var args = inArgs.map(interpretArg);
        if (!restArgs) return args;
        var rest = interpretArg(restArgs);
        if (Array.isArray(rest)) return args.concat.apply(args, rest);
        throw new Error('rest must be an array');
      };
    
      var args = evalArgs(action.args, action.rest);
      return new Function('...args', 'return this.' + action.name + '(...args)').apply(obj, args);
    }
  );

var connections = { };

function getState(store) {
  return connections[store[/* connectionId */1]][/* retainedState */0];
}

function mutateState(state, store) {
  return Curry._1(store[/* component */0][/* send */3], /* `DevToolStateUpdate */Block.polyVar("DevToolStateUpdate", [
                161605709,
                state
              ]));
}

function notifyListeners(store) {
  return List.iter((function (listener) {
                return Curry._1(listener, /* () */0);
              }), store[/* listeners */2]);
}

var PayloadNotFound = Caml_exceptions.create("Connectors-ReductiveDevTools.ConnectionHandler(Store).Exceptions.PayloadNotFound");

var StateNotFound = Caml_exceptions.create("Connectors-ReductiveDevTools.ConnectionHandler(Store).Exceptions.StateNotFound");

var ConnectionNotFound = Caml_exceptions.create("Connectors-ReductiveDevTools.ConnectionHandler(Store).Exceptions.ConnectionNotFound");

function processToogleAction(store, payload, liftedState, meta) {
  var skippedActions = liftedState.skippedActionIds;
  var stagedActions = liftedState.stagedActionIds;
  var computedStates = liftedState.computedStates;
  var actionsById = liftedState.actionsById;
  var id = Belt_Option.getExn(Caml_option.undefined_to_opt(payload.id));
  var idx = skippedActions.indexOf(id);
  var start = stagedActions.indexOf(id);
  var skipped = idx !== -1;
  if (start === -1) {
    return liftedState;
  } else {
    var initialIdx = start - 1 | 0;
    while(skippedActions.includes(initialIdx)) {
      initialIdx = initialIdx - 1 | 0;
    };
    var initialState = Caml_array.caml_array_get(computedStates, initialIdx).state;
    mutateState(Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](initialState), store);
    var preservedActionCount = meta[/* actionCount */2];
    $$Array.iter((function (i) {
            var stagedActionKey = String(Caml_array.caml_array_get(stagedActions, i));
            var targetAction = Belt_Option.getExn(Js_dict.get(actionsById, stagedActionKey)).action;
            Curry._1(store[/* component */0][/* send */3], Utilities$ReductiveDevTools.Serializer[/* deserializeAction */3](targetAction));
            var connectionInfo = Utilities$ReductiveDevTools.unwrap(Js_dict.get(connections, meta[/* connectionId */3]), [
                  ConnectionNotFound,
                  "DevTool connection(id=$connectionId) not found"
                ]);
            var match = Curry._2(connectionInfo[/* retainedReducer */1], Utilities$ReductiveDevTools.Serializer[/* deserializeAction */3](targetAction), connectionInfo[/* retainedState */0]);
            var tmp;
            tmp = typeof match === "number" || match.tag ? connectionInfo[/* retainedState */0] : match[0];
            connectionInfo[/* retainedState */0] = tmp;
            var newState = connectionInfo[/* retainedState */0];
            Caml_array.caml_array_get(computedStates, i).state = Utilities$ReductiveDevTools.Serializer[/* serializeObject */2](newState);
            return /* () */0;
          }), Belt_Array.keep(Belt_Array.range(skipped ? start : start + 1 | 0, stagedActions.length - 1 | 0), (function (i) {
                if (i === start) {
                  return true;
                } else {
                  return skippedActions.indexOf(Caml_array.caml_array_get(stagedActions, i)) === -1;
                }
              })));
    meta[/* actionCount */2] = preservedActionCount;
    if (liftedState.currentStateIndex !== (stagedActions.length - 1 | 0)) {
      var targetState = Caml_array.caml_array_get(computedStates, liftedState.currentStateIndex).state;
      mutateState(Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](targetState), store);
    }
    if (skipped) {
      skippedActions.splice(idx, 1);
    } else {
      skippedActions.push(id);
    }
    meta[/* liftedState */0] = Caml_option.some(liftedState);
    return liftedState;
  }
}

var PayloadNotFound$1 = Caml_exceptions.create("Connectors-ReductiveDevTools.ConnectionHandler(Store).Exceptions.PayloadNotFound");

var StateNotFound$1 = Caml_exceptions.create("Connectors-ReductiveDevTools.ConnectionHandler(Store).Exceptions.StateNotFound");

function processToogleAction$1(store, payload, liftedState, meta) {
  var skippedActions = liftedState.skippedActionIds;
  var stagedActions = liftedState.stagedActionIds;
  var computedStates = liftedState.computedStates;
  var actionsById = liftedState.actionsById;
  var id = Belt_Option.getExn(Caml_option.undefined_to_opt(payload.id));
  var idx = skippedActions.indexOf(id);
  var start = stagedActions.indexOf(id);
  var skipped = idx !== -1;
  if (start === -1) {
    return liftedState;
  } else {
    var initialIdx = start - 1 | 0;
    while(skippedActions.includes(initialIdx)) {
      initialIdx = initialIdx - 1 | 0;
    };
    var initialState = Caml_array.caml_array_get(computedStates, initialIdx).state;
    var state = Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](initialState);
    store[/* state */0] = state;
    var preservedActionCount = meta[/* actionCount */2];
    $$Array.iter((function (i) {
            var stagedActionKey = String(Caml_array.caml_array_get(stagedActions, i));
            var targetAction = Belt_Option.getExn(Js_dict.get(actionsById, stagedActionKey)).action;
            var action = Utilities$ReductiveDevTools.Serializer[/* deserializeAction */3](targetAction);
            Reductive.Store[/* dispatch */4](store, action);
            var newState = Reductive.Store[/* getState */5](store);
            Caml_array.caml_array_get(computedStates, i).state = Utilities$ReductiveDevTools.Serializer[/* serializeObject */2](newState);
            return /* () */0;
          }), Belt_Array.keep(Belt_Array.range(skipped ? start : start + 1 | 0, stagedActions.length - 1 | 0), (function (i) {
                if (i === start) {
                  return true;
                } else {
                  return skippedActions.indexOf(Caml_array.caml_array_get(stagedActions, i)) === -1;
                }
              })));
    meta[/* actionCount */2] = preservedActionCount;
    if (liftedState.currentStateIndex !== (stagedActions.length - 1 | 0)) {
      var targetState = Caml_array.caml_array_get(computedStates, liftedState.currentStateIndex).state;
      var state$1 = Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](targetState);
      store[/* state */0] = state$1;
      notifyListeners(store);
    }
    if (skipped) {
      skippedActions.splice(idx, 1);
    } else {
      skippedActions.push(id);
    }
    meta[/* liftedState */0] = Caml_option.some(liftedState);
    return liftedState;
  }
}

function handle(connection, store, meta, actionCreators, param) {
  var initialState = Reductive.Store[/* getState */5](store);
  Extension$ReductiveDevTools.init(connection, Utilities$ReductiveDevTools.Serializer[/* serializeObject */2](initialState));
  Extension$ReductiveDevTools.subscribe(connection, (function (action) {
          var match = action.type;
          switch (match) {
            case "ACTION" : 
                var action$1 = action;
                var store$1 = store;
                var actionCreators$1 = actionCreators;
                var payload = Utilities$ReductiveDevTools.unwrap(Caml_option.undefined_to_opt(action$1.payload), [
                      PayloadNotFound$1,
                      "action doesn't contain payload while expected"
                    ]);
                if (actionCreators$1 !== undefined) {
                  var action$2 = Curry._2(evalMethod, payload, Caml_option.valFromOption(actionCreators$1));
                  return Reductive.Store[/* dispatch */4](store$1, action$2);
                } else {
                  return /* () */0;
                }
            case "DISPATCH" : 
                var action$3 = action;
                var devTools = connection;
                var store$2 = store;
                var initial = initialState;
                var meta$1 = meta;
                var payload$1 = Utilities$ReductiveDevTools.unwrap(Caml_option.undefined_to_opt(action$3.payload), [
                      PayloadNotFound$1,
                      "action doesn't contain payload while expected"
                    ]);
                var devTools$1 = devTools;
                var store$3 = store$2;
                var payload$2 = payload$1;
                var action$4 = action$3;
                var initial$1 = initial;
                var meta$2 = meta$1;
                var payloadType = payload$2.type;
                var exit = 0;
                switch (payloadType) {
                  case "COMMIT" : 
                      meta$2[/* actionCount */2] = 0;
                      return Extension$ReductiveDevTools.init(devTools$1, Utilities$ReductiveDevTools.Serializer[/* serializeObject */2](Reductive.Store[/* getState */5](store$3)));
                  case "IMPORT_STATE" : 
                      var nextLiftedState = Belt_Option.getExn(Caml_option.undefined_to_opt(payload$2.nextLiftedState));
                      var computedStates = nextLiftedState.computedStates;
                      var targetState = Caml_array.caml_array_get(computedStates, computedStates.length - 1 | 0).state;
                      var state = Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](targetState);
                      store$3[/* state */0] = state;
                      notifyListeners(store$3);
                      meta$2[/* actionCount */2] = nextLiftedState.nextActionId - 1 | 0;
                      return Extension$ReductiveDevTools.send(devTools$1, null, nextLiftedState);
                  case "JUMP_TO_ACTION" : 
                  case "JUMP_TO_STATE" : 
                      exit = 1;
                      break;
                  case "RESET" : 
                      store$3[/* state */0] = initial$1;
                      notifyListeners(store$3);
                      meta$2[/* actionCount */2] = 0;
                      return Extension$ReductiveDevTools.init(devTools$1, Utilities$ReductiveDevTools.Serializer[/* serializeObject */2](Reductive.Store[/* getState */5](store$3)));
                  case "ROLLBACK" : 
                      var stateString = Utilities$ReductiveDevTools.unwrap(Caml_option.undefined_to_opt(action$4.state), [
                            StateNotFound$1,
                            "action(" + (String(payloadType) + ") doesn\'t contain state while expected")
                          ]);
                      var state$1 = Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](Utilities$ReductiveDevTools.parse(stateString));
                      store$3[/* state */0] = state$1;
                      notifyListeners(store$3);
                      meta$2[/* actionCount */2] = 0;
                      return Extension$ReductiveDevTools.init(devTools$1, Utilities$ReductiveDevTools.Serializer[/* serializeObject */2](Reductive.Store[/* getState */5](store$3)));
                  case "LOCK_CHANGES" : 
                  case "SWEEP" : 
                      return /* () */0;
                  case "TOGGLE_ACTION" : 
                      var stateString$1 = Utilities$ReductiveDevTools.unwrap(Caml_option.undefined_to_opt(action$4.state), [
                            StateNotFound$1,
                            "action(" + (String(payloadType) + ") doesn\'t contain state while expected")
                          ]);
                      if (Belt_Option.isSome(meta$2[/* rewindActionIdx */1]) && Belt_Option.getExn(meta$2[/* rewindActionIdx */1]) >= meta$2[/* actionCount */2] || Belt_Option.isNone(meta$2[/* rewindActionIdx */1])) {
                        var liftedState = Utilities$ReductiveDevTools.parse(stateString$1);
                        Extension$ReductiveDevTools.send(devTools$1, null, processToogleAction$1(store$3, payload$2, liftedState, meta$2));
                        return notifyListeners(store$3);
                      } else {
                        return 0;
                      }
                  default:
                    return /* () */0;
                }
                if (exit === 1) {
                  var stateString$2 = Utilities$ReductiveDevTools.unwrap(Caml_option.undefined_to_opt(action$4.state), [
                        StateNotFound$1,
                        "action(" + (String(payloadType) + ") doesn\'t contain state while expected")
                      ]);
                  var actionId = Belt_Option.getExn(Caml_option.undefined_to_opt(payload$2.actionId));
                  var match$1 = actionId === meta$2[/* actionCount */2];
                  meta$2[/* rewindActionIdx */1] = match$1 ? undefined : actionId;
                  var match$2 = meta$2[/* liftedState */0];
                  if (match$2 !== undefined) {
                    var liftedState$1 = Caml_option.valFromOption(match$2);
                    var actionInLiftedStateRange = actionId < liftedState$1.nextActionId;
                    if (actionInLiftedStateRange) {
                      var skippedActions = liftedState$1.skippedActionIds;
                      var computedStates$1 = liftedState$1.computedStates;
                      var nonSkippedIdx = actionId;
                      while(skippedActions.includes(nonSkippedIdx)) {
                        nonSkippedIdx = nonSkippedIdx - 1 | 0;
                      };
                      var targetState$1 = Caml_array.caml_array_get(computedStates$1, nonSkippedIdx).state;
                      var state$2 = Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](targetState$1);
                      store$3[/* state */0] = state$2;
                    } else {
                      var state$3 = Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](Utilities$ReductiveDevTools.parse(stateString$2));
                      store$3[/* state */0] = state$3;
                    }
                  } else {
                    var state$4 = Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](Utilities$ReductiveDevTools.parse(stateString$2));
                    store$3[/* state */0] = state$4;
                  }
                  return notifyListeners(store$3);
                }
                case "START" : 
                return /* () */0;
            default:
              return /* () */0;
          }
        }));
  return /* () */0;
}

function defaultOptions(connectionId) {
  return {
          name: connectionId,
          features: {
            pause: true,
            lock: false,
            persist: true,
            export: true,
            import: "custom",
            jump: true,
            skip: false,
            reorder: false,
            dispatch: true
          }
        };
}

function constructOptions(options, defaults) {
  var target = Object.assign(defaults, options);
  return Object.assign(target, {
              serialize: {
                symbol: true
              },
              features: Object.assign(target["features"], {
                    lock: false,
                    reorder: false,
                    export: true,
                    import: "custom"
                  })
            });
}

function reductiveEnhancer(options, storeCreator, reducer, preloadedState, enhancer, param) {
  var targetOptions = constructOptions(options, defaultOptions("ReductiveDevTools"));
  var devTools = Extension$ReductiveDevTools.connect(Extension$ReductiveDevTools.devToolsEnhancer, targetOptions);
  var meta = /* record */Block.record([
      "liftedState",
      "rewindActionIdx",
      "actionCount",
      "connectionId"
    ], [
      undefined,
      undefined,
      0,
      Belt_Option.getWithDefault(Caml_option.undefined_to_opt(targetOptions.name), "ReductiveDevTools")
    ]);
  var devToolsDispatch = function (store, next, action) {
    var match = meta[/* rewindActionIdx */1];
    if (match !== undefined && match < meta[/* actionCount */2]) {
      return 0;
    } else {
      var store$1 = store;
      var next$1 = next;
      var action$1 = action;
      if (enhancer !== undefined) {
        Curry._3(enhancer, store$1, next$1, action$1);
      } else {
        Curry._1(next$1, action$1);
      }
      meta[/* actionCount */2] = meta[/* actionCount */2] + 1 | 0;
      return Extension$ReductiveDevTools.send(devTools, Utilities$ReductiveDevTools.Serializer[/* serializeAction */1](action$1), Utilities$ReductiveDevTools.Serializer[/* serializeObject */2](Reductive.Store[/* getState */5](store$1)));
    }
  };
  var store = Curry._4(storeCreator, reducer, preloadedState, devToolsDispatch, /* () */0);
  var actionCreators = targetOptions.actionCreators;
  handle(devTools, store, meta, actionCreators === undefined ? undefined : Caml_option.some(actionCreators), /* () */0);
  return store;
}

function register(connectionId, component, options, param) {
  var targetOptions = options !== undefined ? constructOptions(Caml_option.valFromOption(options), defaultOptions(connectionId)) : defaultOptions(connectionId);
  var devTools = Extension$ReductiveDevTools.connect(Extension$ReductiveDevTools.devToolsEnhancer, targetOptions);
  var actionCreators = targetOptions.actionCreators;
  var connectionInfo = /* record */Block.record([
      "retainedState",
      "retainedReducer",
      "connection",
      "meta"
    ], [
      component[/* state */1],
      (function (_action, _state) {
          return /* NoUpdate */0;
        }),
      devTools,
      Block.record([
          "liftedState",
          "rewindActionIdx",
          "actionCount",
          "connectionId"
        ], [
          undefined,
          undefined,
          0,
          connectionId
        ])
    ]);
  connections[connectionId] = connectionInfo;
  var connection = devTools;
  var store = /* record */Block.record([
      "component",
      "connectionId"
    ], [
      component,
      connectionId
    ]);
  var meta = connectionInfo[/* meta */3];
  var actionCreators$1 = actionCreators === undefined ? undefined : Caml_option.some(actionCreators);
  var initialState = getState(store);
  Extension$ReductiveDevTools.init(connection, Utilities$ReductiveDevTools.Serializer[/* serializeObject */2](initialState));
  Extension$ReductiveDevTools.subscribe(connection, (function (action) {
          var match = action.type;
          switch (match) {
            case "ACTION" : 
                var action$1 = action;
                var store$1 = store;
                var actionCreators$2 = actionCreators$1;
                var payload = Utilities$ReductiveDevTools.unwrap(Caml_option.undefined_to_opt(action$1.payload), [
                      PayloadNotFound,
                      "action doesn't contain payload while expected"
                    ]);
                if (actionCreators$2 !== undefined) {
                  return Curry._1(store$1[/* component */0][/* send */3], Curry._2(evalMethod, payload, Caml_option.valFromOption(actionCreators$2)));
                } else {
                  return /* () */0;
                }
            case "DISPATCH" : 
                var action$2 = action;
                var devTools = connection;
                var store$2 = store;
                var initial = initialState;
                var meta$1 = meta;
                var payload$1 = Utilities$ReductiveDevTools.unwrap(Caml_option.undefined_to_opt(action$2.payload), [
                      PayloadNotFound,
                      "action doesn't contain payload while expected"
                    ]);
                var devTools$1 = devTools;
                var store$3 = store$2;
                var payload$2 = payload$1;
                var action$3 = action$2;
                var initial$1 = initial;
                var meta$2 = meta$1;
                var payloadType = payload$2.type;
                var exit = 0;
                switch (payloadType) {
                  case "COMMIT" : 
                      meta$2[/* actionCount */2] = 0;
                      return Extension$ReductiveDevTools.init(devTools$1, Utilities$ReductiveDevTools.Serializer[/* serializeObject */2](getState(store$3)));
                  case "IMPORT_STATE" : 
                      var nextLiftedState = Belt_Option.getExn(Caml_option.undefined_to_opt(payload$2.nextLiftedState));
                      var computedStates = nextLiftedState.computedStates;
                      var targetState = Caml_array.caml_array_get(computedStates, computedStates.length - 1 | 0).state;
                      mutateState(Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](targetState), store$3);
                      meta$2[/* actionCount */2] = nextLiftedState.nextActionId - 1 | 0;
                      return Extension$ReductiveDevTools.send(devTools$1, null, nextLiftedState);
                  case "JUMP_TO_ACTION" : 
                  case "JUMP_TO_STATE" : 
                      exit = 1;
                      break;
                  case "RESET" : 
                      mutateState(initial$1, store$3);
                      meta$2[/* actionCount */2] = 0;
                      return Extension$ReductiveDevTools.init(devTools$1, Utilities$ReductiveDevTools.Serializer[/* serializeObject */2](getState(store$3)));
                  case "ROLLBACK" : 
                      var stateString = Utilities$ReductiveDevTools.unwrap(Caml_option.undefined_to_opt(action$3.state), [
                            StateNotFound,
                            "action(" + (String(payloadType) + ") doesn\'t contain state while expected")
                          ]);
                      mutateState(Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](Utilities$ReductiveDevTools.parse(stateString)), store$3);
                      meta$2[/* actionCount */2] = 0;
                      return Extension$ReductiveDevTools.init(devTools$1, Utilities$ReductiveDevTools.Serializer[/* serializeObject */2](getState(store$3)));
                  case "LOCK_CHANGES" : 
                  case "SWEEP" : 
                      return /* () */0;
                  case "TOGGLE_ACTION" : 
                      var stateString$1 = Utilities$ReductiveDevTools.unwrap(Caml_option.undefined_to_opt(action$3.state), [
                            StateNotFound,
                            "action(" + (String(payloadType) + ") doesn\'t contain state while expected")
                          ]);
                      if (Belt_Option.isSome(meta$2[/* rewindActionIdx */1]) && Belt_Option.getExn(meta$2[/* rewindActionIdx */1]) >= meta$2[/* actionCount */2] || Belt_Option.isNone(meta$2[/* rewindActionIdx */1])) {
                        var liftedState = Utilities$ReductiveDevTools.parse(stateString$1);
                        Extension$ReductiveDevTools.send(devTools$1, null, processToogleAction(store$3, payload$2, liftedState, meta$2));
                        return /* () */0;
                      } else {
                        return 0;
                      }
                  default:
                    return /* () */0;
                }
                if (exit === 1) {
                  var stateString$2 = Utilities$ReductiveDevTools.unwrap(Caml_option.undefined_to_opt(action$3.state), [
                        StateNotFound,
                        "action(" + (String(payloadType) + ") doesn\'t contain state while expected")
                      ]);
                  var actionId = Belt_Option.getExn(Caml_option.undefined_to_opt(payload$2.actionId));
                  var match$1 = actionId === meta$2[/* actionCount */2];
                  meta$2[/* rewindActionIdx */1] = match$1 ? undefined : actionId;
                  var match$2 = meta$2[/* liftedState */0];
                  if (match$2 !== undefined) {
                    var liftedState$1 = Caml_option.valFromOption(match$2);
                    var actionInLiftedStateRange = actionId < liftedState$1.nextActionId;
                    if (actionInLiftedStateRange) {
                      var skippedActions = liftedState$1.skippedActionIds;
                      var computedStates$1 = liftedState$1.computedStates;
                      var nonSkippedIdx = actionId;
                      while(skippedActions.includes(nonSkippedIdx)) {
                        nonSkippedIdx = nonSkippedIdx - 1 | 0;
                      };
                      var targetState$1 = Caml_array.caml_array_get(computedStates$1, nonSkippedIdx).state;
                      mutateState(Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](targetState$1), store$3);
                    } else {
                      mutateState(Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](Utilities$ReductiveDevTools.parse(stateString$2)), store$3);
                    }
                  } else {
                    mutateState(Utilities$ReductiveDevTools.Serializer[/* deserializeObject */4](Utilities$ReductiveDevTools.parse(stateString$2)), store$3);
                  }
                  return /* () */0;
                }
                case "START" : 
                return /* () */0;
            default:
              return /* () */0;
          }
        }));
  return /* () */0;
}

function unsubscribe(connectionId) {
  var connectionInfo = Utilities$ReductiveDevTools.unwrap(Js_dict.get(connections, connectionId), [
        ConnectionNotFound,
        "DevTool connection(id=$connectionId) not found"
      ]);
  Js_dict.unsafeDeleteKey(connections, connectionId);
  return Extension$ReductiveDevTools.unsubscribe(connectionInfo[/* connection */2]);
}

function componentReducerEnhancer(connectionId, reducer, action, state) {
  var match = Js_dict.get(connections, connectionId);
  if (match !== undefined) {
    var connectionInfo = match;
    connectionInfo[/* retainedReducer */1] = reducer;
    var propageAction = function (state, action) {
      var result = Curry._2(reducer, action, state);
      var exit = 0;
      if (typeof action === "number") {
        exit = 1;
      } else if (action[0] !== 161605709) {
        exit = 1;
      }
      if (exit === 1) {
        var exit$1 = 0;
        if (typeof result !== "number") {
          switch (result.tag | 0) {
            case 1 : 
                break;
            case 0 : 
            case 2 : 
                exit$1 = 2;
                break;
            
          }
        }
        if (exit$1 === 2) {
          var state$1 = result[0];
          connectionInfo[/* meta */3][/* actionCount */2] = connectionInfo[/* meta */3][/* actionCount */2] + 1 | 0;
          connectionInfo[/* retainedState */0] = state$1;
          Extension$ReductiveDevTools.send(connectionInfo[/* connection */2], Utilities$ReductiveDevTools.Serializer[/* serializeAction */1](action), Utilities$ReductiveDevTools.Serializer[/* serializeObject */2](state$1));
        }
        
      }
      return result;
    };
    var match$1 = connectionInfo[/* meta */3][/* rewindActionIdx */1];
    if (match$1 !== undefined) {
      var isDevToolsStateUpdateAction = typeof action === "number" ? false : action[0] === 161605709;
      if (match$1 >= connectionInfo[/* meta */3][/* actionCount */2] || isDevToolsStateUpdateAction) {
        return propageAction(state, action);
      } else {
        return /* NoUpdate */0;
      }
    } else {
      return propageAction(state, action);
    }
  } else {
    console.warn("reductive-dev-tools connection not found while expected");
    return Curry._2(reducer, action, state);
  }
}

exports.reductiveEnhancer = reductiveEnhancer;
exports.register = register;
exports.unsubscribe = unsubscribe;
exports.componentReducerEnhancer = componentReducerEnhancer;
/* evalMethod Not a pure module */
